### ISSUE TITLE
Followup to #12 - Alternate resource highlight options

### ISSUE THREAD

**Issue by IsaacGraham** [rdutta/runelite-gauntlet#14]
Thanks for so quickly implementing the outline feature on resources.

Could you please add options to toggle icon and outline independently?

Thanks.

**Comment by rdutta** [comment]
> Could you please add options to toggle icon and outline independently?

You can set the icon size or width to 0px to disable any or all of them.

**Comment by IsaacGraham** [comment]
Fair enough, my personal use case is to just remove the icons, and I assume the reverse works turning the outline to 0 if others don't want it.

Thanks for the response.
