### ISSUE TITLE
Feature Request: Reduce render to short/only Hunllef's room during Hunllef fight

### ISSUE THREAD

**Issue by mxiia** [rdutta/runelite-gauntlet#19]

**Comment by rdutta** [comment]
This is already the behavior if I'm not mistaken. If it isn't working this way please provide a screenshot.
```java
		if (plugin.isInHunllef())
		{
			renderTornadoes(graphics2D);
		}
		else
		{
			renderResources(graphics2D);
			renderUtilities(graphics2D);
		}
```
Only tornadoes should be rendered when in the Hunllef room.

**Comment by rdutta** [comment]
Verified in-game that this is already the behavior of the plugin.
