### ISSUE TITLE
Add an audio notificafion such as gauntlet counter

### ISSUE THREAD

**Issue by YvesW** [rdutta/runelite-gauntlet#2]
I'm really excited to start learning the corrupted gauntlet with your plugin enabled! Just had a feature request I wanted to pitch!
I was wondering if something like gauntletcounter.herokuapp.com could be added to the plugin. This could probably be done in multiple ways, based on what would still be ok with Jagex. So, possible features could include:
*Display the timer until the next swap + what to swap to (like the website) in a sidepanel.
*You could also display this onscreen instead of in a sidepanel.
*Use the sound from the website (2-1-mage, 2-1-range etc)
*Automatically start the timer when the Hunllef attacks.
*Automatically add more time to the timer when Hunllef stomps you.
*If the features starting with "automatically" are against Runelite's/Jagex's rules, buttons such as the site has, could be added to the sidepanel. Another option could be customizable shortcuts (e.g. ctrl+q to start the timer, ctrl+e for a stomp).

Thanks in advance!

**Comment by rdutta** [comment]
This plugin is actually a port from a fork of runelite. The [original plugin](https://github.com/xKylee/plugins-source/tree/master/gauntlet/src/main/java/net/runelite/client/plugins/gauntlet) has features like you mention (on screen attack counter, visual indicators etc.), however those features are against Jagex' rules so they were removed in order to get it accepted into the Runelite Plugin Hub. Somehow the tile outline for tornadoes got accepted, but even that was pushing the line if I recall.

You could try running it by the devs in RL discord but I wouldn't count on those features being given the OK.

**Comment by YvesW** [comment]
Ah, interesting to hear! Thought the sound from the website would be okay, since it's basically something you can do completely out of game, but I'll try tunning it by the devs!

**Comment by YvesW** [comment]
As I expected, it seems like it would be okay as long as none of the automated features are added. https://discord.com/channels/301497432909414422/419891709883973642/817534131029671977
So I think adding a sidepanel (only visible when in the Gauntlet area?) with a countdown & sound + trample button + reset button would be fine. Could also add customizable hotkeys.
Let me know if you think it would be too messy for this plugin or something like that; in that case I'll try to make it into a plugin myself at some point probably. Haven't coded Java in a while though and I haven't worked with RL yet. I think I'd be able to base it on the code from e.g. the Zulrah helper?

**Comment by rdutta** [comment]
If it's entirely (mostly?) manual and isn't automatically triggered by animation/projectile/gametick events then it's likely fine rule-wise. A separate standalone plugin sounds more apprppriate, especially if there are no dependencies on this plugin. I haven't played RS in a few months so I'm in the same boat!

**Comment by YvesW** [comment]
Would indeed be entirely manual like the Zulrah Helper plugin. I'll see if I have some time when I get around to learning the Corrupted Gauntlet. Thanks for your input!
