### ISSUE TITLE
Option to only track resources you pick up

### ISSUE THREAD

**Issue by CreativeTechGuy** [rdutta/runelite-gauntlet#25]
Currently, the tracker will decrement the remaining amount of a resource the second that it is dropped. I often see that resource on the ground (eg: weapon frame) and then check the tracker number and it says I don't need anymore because it was already decremented. I'd like the tracker to only update with items that have actually entered my inventory at some point.

A similar thing can easily happen with crystal shards. You are running past an enemy and kill it while moving, it drops shards and not what you are looking for so you keep running and don't pick them up. Now the tracker for shards is off since it considers those shards that you didn't actually take.

**Comment by rdutta** [comment]
I think the issue with this suggestion is dropping resources (common when getting tier2+) and picking them back up. 

It's also messy to constantly track changes to the inventory, afaik.
