### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by Nickert1337** [rdutta/runelite-gauntlet#29]
After todays patch the plugin seems to have dissapeared! :(

**Comment by Aealm** [comment]
Same for me as well :/

**Comment by rdutta** [comment]
A PR has been made to fix the plugin https://github.com/runelite/plugin-hub/pull/4334

Thanks for the heads up

**Comment by Troksii** [comment]
thank you I can't do gauntlet without this plugin.

**Comment by Nickert1337** [comment]
Thank you so much, I'm a retard without this plugin
