### ISSUE TITLE
Corrupted shards and grym leaves dropped by monsters are not included in corner indicator

### ISSUE THREAD

**Issue by noxora** [rdutta/runelite-gauntlet#33]
![image](https://github.com/rdutta/runelite-gauntlet/assets/14023728/dc909c12-d209-454b-a5f9-ed41b9caca60)

Apologies for the poor image, but I chopped a phren root, received 54 shards, and then killed a corrupted rat, which dropped 15 shards. This has been a consistent issue for me, and I could provide more images if needed. I looked at the relevant code and don't see an immediate reason this should happen

**Comment by rdutta** [comment]
I was unable to reproduce this issue. Only thing I can think of is that either you somehow aren't getting loot messages at all (?) or the ironman icon tag is somehow making the [regex](https://github.com/rdutta/runelite-gauntlet/blob/b78770d5b4e2d8f10c8ecc389d9644f41b61a80c/src/main/java/ca/gauntlet/module/maze/ResourceManager.java#LL53C2-L53C2) not match.

**Comment by noxora** [comment]
Hi there! I managed to figure out what's going on. This is caused by some confusion between "The gauntlet" and "gauntlet" plugins. 
It appears that the "gauntlet" plugin hasn't been updated in quite some time, and so its resource tracking is broken, not the plugin's resource tracking. That said, I would still like to propose a new feature to track resources upwards, rather than counting them down from desired numbers to fill the gap in functionality. It would take me quite a while to figure out how to do this, but I'm going to spend an evening on it and see where I get.

**Comment by noxora** [comment]
I've created a PR for this functionality, I could use a bit of help with one part of it, but the rest is done #34
