### ISSUE TITLE
Feature Request: Timer Count down

### ISSUE THREAD

**Issue by evilgenious448** [rdutta/runelite-gauntlet#37]
Hi there,

Is there any chance to add the option for the timer in this plugin to countdown from the maximum in addition to counting up (options for users who prefer different timers). 

I am aware that the gauntlet itself has a countdown timer, however I can't move it into the same place as where I currently have your one, and it is annoying me haha

![image](https://github.com/rdutta/runelite-gauntlet/assets/32331499/be59429e-be7d-4016-a61d-e44e0ca82846)

Thanks heaps!

**Comment by rdutta** [comment]
Since this already exists I'd rather not duplicate the built-in timer.
