### ISSUE TITLE
Fish drop

### ISSUE THREAD

**Issue by namharr1** [rdutta/runelite-gauntlet#4]
Hi , i dont know if you still work with this plugin anymore. But seems like the counter when you fish just apply when your the one who fish it. It does not count on npc drops / when you pick the fish up from an npc drop.

Maybe an possible solution would be:
If its possible to get how many fish there is dropped in the "center room" 
Also count the fish in your inventory to make a total fish.

"center room fish + fish in inventory = total fish"

**Comment by rdutta** [comment]
It checks chat messages to update all loot. I guess it's not looking for "Untradeable drop: # x Raw paddlefish". I'll see if it's easy to fix, but in the meantime you can turn off Loot Notifications and it will register on "Player received a drop: # x Raw paddlefish".

**Comment by rdutta** [comment]
Well I spoke too soon. I tested both versions of the gauntlet with loot notifs on and off, with game filter on and off, and it seems to be working. The only time it didn't update was after changing loot setting while inside (fixed after re-entering).

Can't think of any other reasons why it might not update without more info. Maybe another plugin is preventing the message?

**Comment by laagone** [comment]
I've come across this issue when playing on an account with a space in the username. On `Starch Masks`, it didn't seem to track resources obtained as drops, but fixed itself when I changed name to `ympyra`. I believe that to be the issue.
