### ISSUE TITLE
Overlay resource icon and tile

### ISSUE THREAD

**Issue by axeleebob** [rdutta/runelite-gauntlet#5]
I would like to propose a feature. This is my first time contributing to GitHub so let me know if this is the wrong place!

In the Resources tab, can you split the "Overlay resource icon and tile" feature so that fishing pools are a separate toggleable option?

**Comment by rdutta** [comment]
![h85ye95WnF](https://user-images.githubusercontent.com/38548565/128812075-8cd7f7e5-9d74-4ea9-a965-a39f99709710.png)

commit 986946dd70e97844ef249dde4a53b3c545a45694

This is the right place. I've split out resource overlays into its own section and added individual config items for each resource.

Only problem is that I don't have membership/I'm not actively playing osrs, so I can't test it. If someone can test (maybe ask RL discord) and report back here that it works as intended, I will get it updated in the plugin hub.
